# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood'),
        ),
    ]
