# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20191029_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='businesses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.User', unique=True),
        ),
    ]
