# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0009_auto_20191030_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='My_User',
        ),
        migrations.AlterField(
            model_name='businesses',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood', unique=True),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood'),
        ),
    ]
